-- Vista de detalle para el Stock Actual (Drill-down)
-- Esta vista identifica dónde está cada expediente que se considera "en stock" actualmente
DROP MATERIALIZED VIEW IF EXISTS mvw_stock_actual_detalle CASCADE;

CREATE MATERIALIZED VIEW mvw_stock_actual_detalle AS
WITH ultimos_pases AS (
    -- Obtener el último movimiento de cada expediente
    SELECT id_expediente, MAX(fecha) as max_fecha
    FROM mvw_ee_pases_secgdu
    GROUP BY id_expediente
),
expedientes_info AS (
    SELECT id_expediente, trata, descripcion, 
           CASE WHEN estado ILIKE 'Subsanaci%' OR estado ILIKE 'Subsanación%' THEN 1 ELSE 0 END as is_subs
    FROM mvw_expedientes_tratas_secgdu
),
egresos_gedo AS (
    -- Un expediente se considera "salido" si tiene un documento de cierre
    -- Para simplificar la vista de detalle, usamos una lista general de acrónimos de cierre
    SELECT DISTINCT id_expediente
    FROM mvw_datos_gedo_secgdu
    WHERE acronimo IN ('DI', 'IF', 'ANEXO', 'IFMMH', 'IFMAD', 'IFDEX', 'CECNU', 'IFGPA', 'FIPAR', 'IFPCB', 'PPINV', 'IFMOT', 'IFMSC', 'IFMHC', 'PROIN', 'PLINE', 'IFCIS', 'IFSMC', 'IFRSP', 'IFROC', 'IFPCO', 'IFSMI', 'IFPDO', 'IFPEO', 'IFTPT', 'IFOCD', 'IFBRP', 'IFCAO', 'IFCAC')
),
stock_fisico AS (
    SELECT 
        p.id_expediente,
        p.expediente,
        p.destinatario as analista_actual,
        p.fecha as fecha_ing,
        CURRENT_DATE - p.fecha::date as dias_stock,
        ei.trata,
        ei.descripcion,
        ei.is_subs
    FROM mvw_ee_pases_secgdu p
    JOIN expedientes_info ei ON p.id_expediente = ei.id_expediente
    JOIN ultimos_pases up ON p.id_expediente = up.id_expediente AND p.fecha = up.max_fecha
    LEFT JOIN egresos_gedo eg ON p.id_expediente = eg.id_expediente
    WHERE eg.id_expediente IS NULL -- No tiene egreso GEDO
      AND p.estado != 'Guarda Temporal' -- No está en guarda
      AND p.destinatario != 'GUARDA TEMPORAL'
)
SELECT 
    sf.*,
    CASE 
        -- CATASTRO
        WHEN analista_actual IN ('ACOSTAPA', 'AFAHLER', 'AGUSMAZZONI', 'ALEALFONSIN', 'ALEGREM', 'ARGENTOES', 'BARTROLIG', 'CABRERAM', 'CANALEAL', 'CARBONELLIM', 'CHIANETTAR', 'CIOPKOG', 'CISTERNACA', 'COHENCAD', 'CONTIL', 'CONVERTID', 'DELGADODE', 'DGROC-CIC', 'DGROC-COPIAPLANO', 'DGROC-DCATDES', 'DGROC-DCATMEN', 'DGROC-DCATPOL', 'DGROC-DCATTIT', 'DIBIASEO', 'DIEZGASTON', 'DIHARCEP', 'DURSIM', 'ECIJAN', 'FMARCHISELLA', 'FOLLONIERLE', 'FREIXASC', 'GARCIASIL', 'GILESJP', 'GONZALEZAMA', 'GONZALEZHORAC', 'GUZMANO', 'IGARZABALP', 'JTIRADO', 'LAGUNAMA', 'LBELLY', 'LOISIG', 'LUCCIC', 'M.NAPOLI', 'MALATTOR', 'MANNOP', 'MARCHETTIJ', 'MHOSBALIKCIYAN', 'MOSCOVICHA', 'NCITRANGOLO', 'NOGUERAH', 'NPONZO', 'NQUINTERNO', 'PONZOS', 'ROLDANG', 'SALGUEROM', 'SORIAANDREA', 'TARRUA', 'TAVELLAE', 'VEGAJ', 'VILLAGI', 'WVIRGILIO') THEN 'catastro'
        -- INSTALACIONES
        WHEN analista_actual IN ('AQUINOLUCAS', 'ARENAJ', 'ARGUELLOJ', 'BATALLANJ', 'BENITOG', 'BRIANMARTINEZ', 'CORNAZM', 'DGROC-DCIMYE', 'DGROC-ELECTRICAS', 'FICARRAR', 'GAGLIARDIA', 'LOPARDOC', 'QUEIJASGUILLINP', 'ROBLEDOJO', 'ROLDANMI', 'RUDAC', 'SARIDISD', 'TOLESANOA', 'AURENA', 'BATALLANGE', 'BRITANP', 'DGROC-DCIELEV', 'DGROC-ELEVADORES', 'DGROC-OBSDCIELEV', 'GUARDADOB', 'JDECIMA', 'PEREZGA', 'RODRIGUEZESTEBAN', 'RODRIGUEZNE', 'SILESC', 'VILLAGAB', 'ABCRAGNO', 'AGARCIAFIGUEROA', 'CABRERAARI', 'CAFELICE', 'CAPOZZOG', 'CSALGUERO', 'DARANGURI', 'DGROC-DCIDITI', 'DGROC-ESPERAAGCINCENDIO', 'DGROC-INCENDIO', 'DMOFFA', 'FUHRY', 'GONMAR', 'J.OLIVERA', 'LOPEZFE', 'MARIANELAROCARO', 'MBALDOME', 'MLMAMONE', 'MTRENQUE', 'NIEVAL', 'PCHERBENCO', 'RADAA', 'RIOSFE', 'ROMANOFLA', 'SANTACRUZ', 'CANTARELLTORRES', 'CIRIAE', 'LOIACONOANA', 'MCDIAMANTI', 'POUSAF', 'ARGUELLOSOL', 'COSSM', 'DGROC-SANITARIAS', 'EIERACI', 'HAMALAG', 'RUIZMA', 'BRITANG', 'DGROC-TERMICAS', 'ENCISOROMERO', 'PITTERIE', 'WIERZBICKIIGOR') THEN 'instalaciones'
        -- REGULARIZACION
        WHEN analista_actual IN ('AGUEROJO', 'AKRACOFF', 'ALVAREZ.M', 'ARAOZLUIS', 'ATENCIOAL', 'DALBORAF', 'DGROC-ESPERAINSTALACIONES', 'DGROC-OBRASDEMO', 'ENCISOA', 'EPARLATO', 'ERDOCIAINA', 'JBARRACO', 'JLGARMENDIA', 'JTERRILE', 'MYUSHU', 'S.SANCHEZPAZ', 'SCAVALLARO') THEN 'regularizacion'
        -- CONTABLE
        WHEN analista_actual IN ('AMONTEVERDE', 'AMORINC', 'CARLOSDUARTE', 'CAROJAS', 'COLOTTAP', 'CPENDON', 'DAS', 'DASTUGUEO', 'DEGODOY', 'DGROC-AUTOMAT', 'DGROC-CONTABLE', 'DGROC-DCG', 'DGROC-DESCARGOS', 'DGROC-DTACONT', 'DGROC-DTARPS', 'DGROC-LEGAJOS', 'DGROC-OBRASADMIN', 'DGROC-PENDIENTESDEPAGO', 'DGROC-REVISIONCONTABLE', 'DIAZBAR', 'DKRENZ', 'EDEFEO', 'FABIANSANTILLAN', 'FMHERRERA', 'FSPANTI', 'GARCIASEBA', 'HRICCIARDI', 'JOSEMARIAORTIZ', 'JPOMAR', 'JULILOPARDO', 'LAMORGIAKA', 'LBARRIENTOS', 'LICETB', 'M.ROSSO', 'MARQUEZMAR', 'MARTINEZCLA', 'MLAURITO', 'MMALACALZA', 'NMONTEVERDE', 'NMORENO', 'POVIEDO', 'PRESAF', 'PVACEVEDO', 'RIVERAMA', 'ROBLEDOE', 'RODRIGUEZLEA', 'RODRIGUEZMAGD', 'ROSARIODECRIS', 'SCHULERG', 'SENING', 'SMERMOZ', 'SORIAD', 'SPOSAROAL', 'TATOJ', 'TIRENDIC', 'TOMIPITES', 'VICSOLMORE', 'VILLACRI') THEN 'contable'
        -- ETAPA PROYECTO
        WHEN analista_actual IN ('A.PEREZ', 'AGUSDEMARCO', 'ANTOVERA', 'BELOCURESJ', 'COIROL', 'DBECERRACURITIMA', 'DGROC-OBRASTECNICA', 'DIMASOM', 'DNKAINSKY', 'FORGIONEA', 'GAILLURJP', 'GARRIONDO', 'JOSEFINA.P', 'M.SANCHEZ', 'MARCE.TOSONI', 'MARCETOSONI', 'MARCETOSONI1', 'MBRISA', 'MCANOGARAY', 'MCARLUCCIO', 'MGALLARDOC', 'MSTIBERTI', 'NLOPEZQUIROGA', 'ROCABERTJ', 'SPUET', 'TALAMOM', 'VERA') THEN 'etapa_proyecto'
        -- MORFOLOGIA
        WHEN analista_actual IN ('A.GUZMAN', 'AGARTEAGA', 'ALANDAZURI', 'ALFONSOGA', 'CAROLINAPRADO', 'CGAMARRA', 'CGENTILINI', 'DANCOLOMBO', 'DGIUR-03', 'DGIUR-ADMISIBILIDADMORFO', 'DGIUR-CONSULTASESPECIFICAS', 'DGIUR-CURVERIFICACION', 'DGIUR-DGIUR-PERMISO TEMPRANO', 'DGIUR-VA II', 'ECAYSSIALS', 'EVELYNTORRES', 'FORFANO', 'FOTTOGALLI', 'FRANGARAY', 'GBERNASCONI', 'GCABADGIUR', 'IANELUSTONDO', 'IVALDES', 'LNSPERTINO', 'M.SABATINO', 'MANUELALVELO', 'MILAGROSTOURON', 'MILENAAZULMORENO', 'MLOBIANCOCRIADO', 'MPLANS1', 'MREIDMAN', 'MVOSKIAN', 'NASILANES', 'NCASALE', 'OVERRINA', 'PTEIGA', 'ROCAM', 'SBONDOREVSKY', 'SCABANELLAS', 'SDAVIDOVSKY', 'SVC_DGIURMORFO', 'SVCDGIUR3', 'TOSELLIR', 'VVINICIUS') THEN 'morfologia'
        -- APH
        WHEN analista_actual IN ('CHANTIRRO', 'CHEZOM', 'DAMATOG', 'DESANTISA', 'DGIUR-21', 'DGIUR-ADMISIBILIDADAPH', 'DGIUR-ADMISIMIDIDADAPH', 'GALAMA', 'GONZALEZNIETOR', 'HERENUFE', 'LSANTINMOLINA', 'MARIANALVAREZ', 'NASALVATIERRA', 'PIOLON', 'SVC_DGIURADMAPH', 'VASTAM') THEN 'aph'
        -- USOS
        WHEN analista_actual IN ('ALEPABLOCASTRO', 'ARVASR', 'AUZONMJ', 'BBORGIA', 'BILLAUDL', 'CLAUDIAVARELA', 'DALUNNI', 'DGIUR-12', 'DGIUR-ADMISIBILIDADUSOS', 'DGIUR-EGOUS', 'DIMEGLIOA', 'EDUARDODIAZ', 'ELIANACABRERA', 'FOVERDAGUER', 'JBMENDY', 'JLSCIA', 'JLSCIARROTTA', 'LASALAMI', 'LTROLDAN', 'MAYASTUY', 'MERCADOEA', 'MFALAPPA', 'MIZONCA', 'MOCANA', 'MOURER', 'MPSIMONI', 'MYASTUY', 'PGLEISS', 'PORTAC', 'ROCCOR', 'SOFIAZANI', 'SVC_DGIURUSOS', 'VKAUFMAN') THEN 'usos'
        ELSE 'OTRAS'
    END as gerencia
FROM stock_fisico sf;

CREATE INDEX idx_stock_det_trata ON mvw_stock_actual_detalle (trata);
CREATE INDEX idx_stock_det_analista ON mvw_stock_actual_detalle (analista_actual);
CREATE INDEX idx_stock_det_gerencia ON mvw_stock_actual_detalle (gerencia);
